### ISSUE TITLE
Návrh implementace - důležité otázky (třídní diagram)

### ISSUE THREAD

**Issue by bierdous** [Verevkin-A/UML_diagrams_app#1]
**Formát vstupního souboru?**

- Zvolil bych JSON, přijde mi, že se s tím bude jednoduše pracovat

**Bude pozice tříd součástí vstupního souboru? (x, y souřadnice)**

- Myslím, že by to bylo lepší, aby mohli uživatelé se třídama pohybovat, otázka je jak těžké by to bylo na implementaci. Na druhou stranu, kdybychom to tam nezahrnuli, tak bychom to museli nějak rozumně rozmístit ne, a to bychom taky museli naprogramovat?

**Uložil bych třídy a jejich spojnice do dvou seznamů, přijde mi zbytečné je modelovat jako graf.**

**Návrh formátu souboru (JSON):**

```
{
  "classDiagram": {
    "classes": [
      {
        "name": "testClass",
        "parent": -1,
        "fields": [
          {
            "name": "firstAttr",
            "visibility": "-"
          }
        ],
        "methods": [
          {
            "name": "myTestMethod()",
            "visibility": "+"
          }
        ],
        "isInterface": false
      },
      {
        "name": "testClass2",
        "parent": 0,
        "fields": [
          {
            "name": "firstAttr2",
            "visibility": "-"
          }
        ],
        "methods": [
          {
            "name": "myTestMethod2()",
            "visibility": "+"
          }
        ],
        "isInterface": false
      }
    ],
    "nodes": [
      {
        "from": 0,
        "to": 1,
        "fCard": "0..*",
        "tCard": "1",
        "type": 1
      }
    ]
  }
}
```

**Comment by averevki** [comment]
100/100 well done!
